/*
 * This software is in the public domain because it contains materials 
 * that originally came from the United States Geological Survey, 
 * an agency of the United States Department of Interior. For more 
 * information, see the official USGS copyright policy at 
 * http://www.usgs.gov/visual-id/credit_usgs.html#copyright
 */
package gov.usgs.anss.gui;

import gov.usgs.anss.db.DBConnectionThread;
import gov.usgs.anss.util.Util;
import java.sql.SQLException;
import java.sql.Statement;


/** 
 *
 * @author  ketchum
 * @version 1.0
 */
public final class Logout extends javax.swing.JPanel {

  /** Creates new form Logout */
  private final DBConnectionThread C;
  public Logout(DBConnectionThread Cin) {
    C = Cin;
    initComponents ();
    UC.Look(this);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    button = new javax.swing.JButton();
    newPW = new javax.swing.JPasswordField();
    confirmPW = new javax.swing.JPasswordField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    error = new javax.swing.JTextField();

    setLayout(new java.awt.GridBagLayout());

    button.setText("Logout - Thanks!");
    button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonActionPerformed(evt);
      }
    });
    add(button, new java.awt.GridBagConstraints());

    newPW.setColumns(12);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    add(newPW, gridBagConstraints);

    confirmPW.setColumns(12);
    confirmPW.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        confirmPWActionPerformed(evt);
      }
    });
    confirmPW.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        confirmPWFocusLost(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 7;
    add(confirmPW, gridBagConstraints);

    jLabel2.setText("New Password :");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    add(jLabel2, gridBagConstraints);

    jLabel3.setText("Confirm new :");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    add(jLabel3, gridBagConstraints);

    error.setColumns(35);
    error.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 10;
    add(error, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void confirmPWFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPWFocusLost
    doChangePassword();
  }//GEN-LAST:event_confirmPWFocusLost

  private void confirmPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPWActionPerformed
    // Add your handling code here:
    doChangePassword();

  }//GEN-LAST:event_confirmPWActionPerformed

  private void buttonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
// Add your handling code here:
    doChangePassword();
    Anss.cleanup();
    if(C != null) C.terminate();

    System.exit(0);
  }//GEN-LAST:event_buttonActionPerformed

  private void doChangePassword() {
    String password, confirm;
    String q;

    password = new String(newPW.getPassword());
    confirm = new String(confirmPW.getPassword());
    if(!password.equals(confirm)) {
      error.setBackground(UC.red);
      error.setText("New passwords do not match");
    } else if(password.length() < 5) {
      if(password.length() == 0) return;
      error.setBackground(UC.red);
      error.setText("Password too short (5 char min)");
    } else {
      try {
        String [] connections = {"anss","metadata","gap"};
        for(String db : connections) {
          //Statement stmt = JDBConnection.getConnection("metadata").createStatement();
          Statement stmt = DBConnectionThread.getThread(db).getNewStatement(true);
          q = "SET PASSWORD FOR '"+Login.username+"'@'%' =PASSWORD(" + Util.sqlEscape(password) + ")";
          //q = "UPDATE mysql.user SET password=password('"+Util.sqlEscape(password)+"' WHERE user='"+User.getUser()+"';";
          Util.prt("set password : "+q);
          Util.prt("Update retn="+stmt.executeUpdate(q));
          try {
            q = "SET PASSWORD FOR '"+Login.username+"'@'localhost' =PASSWORD(" + Util.sqlEscape(password) + ")";
            //q = "UPDATE mysql.user SET password=password('"+Util.sqlEscape(password)+"' WHERE user='"+User.getUser()+"';";
            Util.prt("set password : "+q);
            Util.prt("Update retn="+stmt.executeUpdate(q));
          }
          catch(SQLException e) {Util.prt("No localhost for this user.  Error ignored.");}
          gov.usgs.edge.config.UC.Look(error);
          error.setText("Password Updated!");
        }
      }
      catch (SQLException e)
      {
        Util.SQLErrorPrint(e, "SQL set password failed");
        e.printStackTrace();
      }     
    /*try {
        Statement stmt = UC.getConnection().createStatement();
        q = "SET PASSWORD = PASSWORD(" + Util.sqlEscape(password) + ")";
        Util.prt("set password : "+q);
        Util.prt("Update retn="+stmt.executeUpdate(q));
        UC.Look(error);
        error.setText("Password Updated!");
      }
      catch (SQLException e)
      {
        Util.SQLErrorPrint(e, "SQL set password failed");
        e.printStackTrace();
      }*/
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton button;
  private javax.swing.JPasswordField confirmPW;
  private javax.swing.JTextField error;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPasswordField newPW;
  // End of variables declaration//GEN-END:variables

}
