/*
 * This software is in the public domain because it contains materials 
 * that originally came from the United States Geological Survey, 
 * an agency of the United States Department of Interior. For more 
 * information, see the official USGS copyright policy at 
 * http://www.usgs.gov/visual-id/credit_usgs.html#copyright
 */

package gov.usgs.anss.gui;
import gov.usgs.anss.db.DBConnectionThread;
import gov.usgs.anss.tsplot.TSPlotPanel;
import gov.usgs.anss.util.Util;
import java.awt.Dimension;
/** I do not see that this is in use any more.
 *
 * Login.java
 *
 * Created on March 10, 2000, 1:55 PM/*
 * PublicPanel.java
 *
 * Created on April 5, 2008, 4:17 PM
 * @author  davidketchum
 */
public final class PublicPanel extends javax.swing.JFrame {
  private final TSPlotPanel tsplot ;
  private final ReportPanel report;
  private final ReportsPanel reports;
  private GapReportPanel gap;
  private final MultiGapReportPanel gaps;
  /** Creates new form PublicPanel */
  public PublicPanel() {
    initComponents();
    tsplot = new TSPlotPanel(new Dimension(UC.XSIZE, UC.YSIZE));
    tabs.setSize(new Dimension(UC.XSIZE, UC.YSIZE));
    tabs.add("CWBPlot", tsplot);
    
    gaps = new MultiGapReportPanel();
    tabs.add("MultiGap", gaps);
    
    //DEBUGgap = new GapReportPanel();
    tabs.add("Gap",gap);
    
    report = new ReportPanel("anss");
    
    reports = new ReportsPanel("anss");
    tabs.add("Report", reports);
    tabs.add("Build Report", report);

    tsplot.setVisible(true);
  }
  
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tabs = new javax.swing.JTabbedPane();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(tabs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 758, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(25, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .addContainerGap()
        .add(tabs, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 582, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(25, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    Util.setModeGMT();
    Util.setProcess("PublicPanel");
    Util.init("query.prop");
    Util.loadProperties("anss.prop");
    Util.prt("starting argc="+args.length);
    Util.setNoInteractive(true);
    try {
      Util.prt("DBServer="+Util.getProperty("DBServer"));
      Util.prt("StatusDBServer="+Util.getProperty("StatusDBServer"));
      DBConnectionThread dbConnectionThread = new DBConnectionThread(Util.getProperty("StatusDBServer"),"readonly", "status", false, false, "status", Util.getOutput());
      DBConnectionThread dbConnectionThread1 = new DBConnectionThread(Util.getProperty("DBServer"),"readonly", "anss", false, false, "anss", Util.getOutput());
    }
    catch(InstantiationException e) {
      Util.prt("Wierd instantiation e="+e);
      e.printStackTrace();
      System.exit(1);
    }

    for(int i=0; i<args.length; i++) Util.prt("arg "+i+" is "+args[i]);
    //PublicPanel cd = new PublicPanel();
    //cd.setVisible(true);
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new PublicPanel().setVisible(true);
      }
    });
  }

 
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTabbedPane tabs;
  // End of variables declaration//GEN-END:variables
  
}
