/*
 * Copyright 2010, United States Geological Survey or
 * third-party contributors as indicated by the @author tags.
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
package gov.usgs.anss.metadatagui;
/*
 * Logoutx.java
 *
 * Created on March 15, 2000, 1:57 PM
 */
import gov.usgs.anss.util.Util;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;


/** 
 *
 * @author  ketchum
 * @version 
 */
public class Logoutx extends javax.swing.JPanel {

  /**
   * Creates new form Logoutx
   */
  private Connection C;
  public Logoutx(Connection Cin) {
    C = Cin;
    initComponents ();
    UC.Look(this);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    button = new javax.swing.JButton();
    newPW = new javax.swing.JPasswordField();
    confirmPW = new javax.swing.JPasswordField();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    error = new javax.swing.JTextField();

    setLayout(new java.awt.GridBagLayout());

    button.setText("Logout - Thanks!");
    button.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        buttonActionPerformed(evt);
      }
    });

    add(button, new java.awt.GridBagConstraints());

    newPW.setColumns(12);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 5;
    add(newPW, gridBagConstraints);

    confirmPW.setColumns(12);
    confirmPW.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        confirmPWActionPerformed(evt);
      }
    });
    confirmPW.addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusLost(java.awt.event.FocusEvent evt) {
        confirmPWFocusLost(evt);
      }
    });

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 7;
    add(confirmPW, gridBagConstraints);

    jLabel2.setText("New Password :");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 5;
    add(jLabel2, gridBagConstraints);

    jLabel3.setText("Confirm new :");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 7;
    add(jLabel3, gridBagConstraints);

    error.setColumns(35);
    error.setFont(new java.awt.Font("Monospaced", 0, 12));
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 10;
    add(error, gridBagConstraints);

  }// </editor-fold>//GEN-END:initComponents

  private void confirmPWFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_confirmPWFocusLost
// TODO add your handling code here:
    doChangePassword();
  }//GEN-LAST:event_confirmPWFocusLost

  private void confirmPWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPWActionPerformed
    // Add your handling code here:
    doChangePassword();

  }//GEN-LAST:event_confirmPWActionPerformed

  private void buttonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
// Add your handling code here:
    doChangePassword();
    MetaGUI.cleanup();
    try {
      C.close();
    } catch(SQLException e) {
      Util.prt("Got an SQL exception on close in Logout");
    }
    System.exit(0);
  }//GEN-LAST:event_buttonActionPerformed

  private void doChangePassword() {
    String password, confirm;
    String q;

    password = new String(newPW.getPassword());
    confirm = new String(confirmPW.getPassword());
    if(!password.equals(confirm)) {
      error.setBackground(UC.red);
      error.setText("New passwords do not match");
    } else if(password.length() < 5) {
      if(password.length() == 0) return;
      error.setBackground(UC.red);
      error.setText("Password too short (5 char min)");
    } else {
      try {
        Statement stmt = UC.getConnection().createStatement();
        q = "SET PASSWORD = PASSWORD(" + Util.sqlEscape(password) + ")";
        Util.prt("set password : "+q);
        Util.prt("Update retn="+stmt.executeUpdate(q));
        UC.Look(error);
        error.setText("Password Updated!");
      }
      catch (SQLException e)
      {
        Util.SQLErrorPrint(e, "SQL set password failed");
        e.printStackTrace();
      }
    }
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton button;
  private javax.swing.JPasswordField confirmPW;
  private javax.swing.JTextField error;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPasswordField newPW;
  // End of variables declaration//GEN-END:variables

}
