/*
 *  This software is in the public domain because it contains materials 
 *  that originally came from the United States Geological Survey, 
 *  an agency of the United States Department of Interior. For more 
 *  information, see the official USGS copyright policy at 
 *  http://www.usgs.gov/visual-id/credit_usgs.html#copyright
 */
package gov.usgs.edge.config;

/**
 *
 * @author bmielke
 */
public class PickerChannelsSubPanel extends javax.swing.JPanel {
  private final PickerPanel pickerPanel;
  private final int channelId;
  private final int pickerId;
  private final String channelName;
  private final String pickerName;

  /**
   * Creates new form PickerChannelsSubPanel
   * @param pickerPanel
   * @param channelId
   * @param channelName
   * @param pickerId
   * @param pickerName
   */
  public PickerChannelsSubPanel(PickerPanel pickerPanel,int channelId,String channelName,
          int pickerId,String pickerName) {
    this.channelId = channelId;
    this.pickerId = pickerId;
    this.channelName = channelName;
    this.pickerName = pickerName;
    this.pickerPanel = pickerPanel;
    gov.usgs.edge.config.UC.Look(this);
    initComponents();
  }
  
  public int getChannelId() {
    return channelId;
  }
  
  public int getPickerId() {
    return pickerId;
  }
  
  public boolean getSelected() {
    return channelSelectButton.isSelected();
  }
  
  public void setSelected(boolean selected) {
    channelSelectButton.setSelected(selected);
  }
  
  public void setText(String text) {
    channelSelectButton.setText(text);
  }
  
  public String getChannelName() {
    return channelName;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    channelSelectButton = new javax.swing.JRadioButton();

    channelSelectButton.setText("NNSSSSSCCCLL");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(channelSelectButton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(channelSelectButton)
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JRadioButton channelSelectButton;
  // End of variables declaration//GEN-END:variables
}
