/*
 * This software is in the public domain because it contains materials 
 * that originally came from the United States Geological Survey, 
 * an agency of the United States Department of Interior. For more 
 * information, see the official USGS copyright policy at 
 * http://www.usgs.gov/visual-id/credit_usgs.html#copyright
 */

/*
 * PopupForm.java
 *
 * Created on February 20, 2008, 9:29 AM
 */

package gov.usgs.edge.config;
import gov.usgs.anss.util.Util;
import javax.swing.JComponent;
/**
 *
 * @author  davidketchum
 */
public class PopupForm extends javax.swing.JFrame {
  ShutdownPopupForm shutdown;
  JComponent parent;
  String holdtext=null;

  /** Creates new form PopupForm */
  public PopupForm(JComponent par) {
    
    initComponents();
    parent = par;
    setVisible(false);
    shutdown = new ShutdownPopupForm(this);
    this.setDefaultCloseOperation(javax.swing.JFrame.HIDE_ON_CLOSE);
    Runtime.getRuntime().addShutdownHook(shutdown);
    Look();
  }
  private void Look() {
    UC.Look(this);                    // Set color background
    
  }
  
  public void setText(String s) {
    holdtext=s;
    text.setText(holdtext);
    text.setCaretPosition(0);
  } 
  public String getText() {
    try {
      return text.getText();
    }
    catch(RuntimeException e) {
      Util.prt("PopUpForm runtime handled in getText()");
      e.printStackTrace();
      return "";
    }
  }

  public void setContentHtml(boolean s) {
    if (s) text.setContentType("text/html");
//    else text.setContentType("text/plain");
  }  
  
  public void displayForm(boolean t) {
    if(t) {
      text.setText(holdtext);
      text.setCaretPosition(0);
      setVisible(true);
    }
    else setVisible(false);
    
  }
  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    text = new javax.swing.JTextPane();
    dismiss = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setFocusable(false);
    addComponentListener(new java.awt.event.ComponentAdapter() {
      public void componentMoved(java.awt.event.ComponentEvent evt) {
        formComponentMoved(evt);
      }
    });
    addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        formFocusGained(evt);
      }
    });

    jScrollPane1.setMinimumSize(new java.awt.Dimension(560, 900));
    jScrollPane1.setPreferredSize(new java.awt.Dimension(560, 900));
    jScrollPane1.setViewportView(text);

    dismiss.setText("Dismiss");
    dismiss.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        dismissActionPerformed(evt);
      }
    });

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
          .add(layout.createSequentialGroup()
            .add(33, 33, 33)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 831, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
          .add(layout.createSequentialGroup()
            .add(344, 344, 344)
            .add(dismiss)))
        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
      .add(layout.createSequentialGroup()
        .add(26, 26, 26)
        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 721, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        .add(58, 58, 58)
        .add(dismiss)
        .addContainerGap(52, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void dismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissActionPerformed
// TODO add your handling code here:
    //removeAll();
    if (parent ==null) return;
    if (parent instanceof EdgemomPanel){
      EdgemomPanel tmp = (EdgemomPanel)parent;
      tmp.dismisspopup();
      }
    if (parent instanceof EdgemomsetupPanel){
        setVisible(false);
    }
    else if (parent instanceof EdgethreadPanel){ 
      EdgethreadPanel tmp = (EdgethreadPanel)parent;
      tmp.dismisspopup();
      }    
    else if (parent instanceof HelpPanel2){ 
      HelpPanel2 tmp = (HelpPanel2)parent;
      tmp.dismisspopup();
      }
  }//GEN-LAST:event_dismissActionPerformed

  private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
    // TODO add your handling code here:
    if (parent==null) return;
    parent.requestFocus();
  }//GEN-LAST:event_formFocusGained

  private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
    // TODO add your handling code here:
    if (parent ==null) return;
    if (parent instanceof EdgemomPanel){ 
      EdgemomPanel tmp = (EdgemomPanel)parent;
      tmp.setPopupXY();
      }
    else if (parent instanceof EdgethreadPanel){ 
      EdgethreadPanel tmp = (EdgethreadPanel)parent;
      tmp.setPopupXY();
      }
  }//GEN-LAST:event_formComponentMoved
  
  /**
   * @param args the command line arguments
   */
  private static PopupForm popup;
  class ShutdownPopupForm extends Thread {
    PopupForm popup;
    public ShutdownPopupForm(PopupForm pop)  {
      popup = pop;
    }
    @Override
    public void run() {
      //Util.prta("Closing Popup form");
      //popup.dispose();
    }
  }
  public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
      @Override
      public void run() {
        EdgemomPanel parent=new EdgemomPanel();
        popup = new PopupForm( parent );
        //popup.setText("");
      }
      
    });
    

    try {Thread.sleep(1000);} catch(InterruptedException e) {}
    popup.setText("USAAM  BHZ   DAS Status at 2008-02-20 17:39   clockQual=100 type=Q330\n"+
      "MassPos(1-3): 20 20 20 (ch 4-6): 24 -3 -11\n"+
      "temp=12 temp2=0 volt1=13.5 volt2=0.0\n"+
      "Time base=1966 pllint=0 gpbits=0xc4 pllbits=0x0\n"+
      "\n"+
      "     TCPSTATION  IP=067.047.200.002 mask=255.255.255.248 BackHaul=Public  LastMile=G2G4R \n"+
      "  Q330 config - use tunnel=False   Single IP(POC Site)=false\n"+
      "0 US AAM AAM 0747 0x10000044dcbbb73  hostport=11228->9228:67.47.200.3/5330 Notunnel\n"+
      "#pings=122 min=975 max=32291 avg=1694 ms. #seqerr=0 over last 7260 secs. last at 2008-02-20 17:40:15\n"+
      "\n"+
      "   NSNSTATION net=1 node=28 type=Q330 higain=True seisType=STS-2 lowgain=True DAS=Q330SR  seed network=US\n"+
      "\n"+
      "   SNWSTATION  lat=42.3012 long=-83.6567 elev=172.0 Ann Arbor, Michigan, USA ID=472\n"+
      "SNW Groups : BH-Public Internet, IMPORT BuRec, NOC-Hughes, Q330, View Golden, View McMillan, \n"+
      "SNWRule : Q330    Dynamic Groups : Proc=MSServer cpu=edge7 remIp= remproc= sort=\n"+
      "* CHANNEL(NSCL)USAAM  BHZ\n"+
      "* NETWORK      US\n"+
      "* STATION      AAM  \n"+
      "* COMPONENT    BHZ\n"+
      "* LOCATION       \n"+
      "* CREATED      2008/02/20 17:40:25.72\n"+
      "* EFFECTIVE    2005-06-04 00:00:00.0\n"+
      "* ENDDATE      2037-12-31 23:59:59.0\n"+
      "* PARSE FLAGS        \n"+
      "* INPUT UNIT   NM\n"+
      "* OUTPUT UNIT  COUNT\n"+
      "* DESCRIPTION  Ann Arbor, Michigan, USA\n"+
      "* RATE (HZ)    40.0\n"+
      "* OWNER        USNSN (AAM)\n"+
      "* COORD(NEIC)  US AAM:  42.3012  -83.6567  172.0\n"+
      "* COORD(SEED)  US AAM:  42.3012  -83.6567  172.0\n"+
      "* ORIENTATION  US AAM   -- BHZ:     0.0 -90.0    0.0\n"+
      "* LAT-SEED     42.3012\n"+
      "* LONG-SEED    -83.6567\n"+
      "* ELEV-SEED    172.0\n"+
      "* DEPTH        0.0\n"+
      "* DIP          -90.0\n"+
      "* AZIMUTH      0.0\n"+
      "* INSTRMNTTYPE STS2-I=90015=Gen=Q330SR=1274\n"+
      "* INSTRMNTGAIN 1.5000E03\n"+
      "* SENS-SEED    6.2914E08\n"+
      "* SENS-CALC    6.2914E08\n"+
      "* A0-SEED      4.8539E07\n"+
      "* A0-CALC      4.8539E07\n"+
      "* SEEDFLAGS    CG\n"+
      "* ****\n"+
      "CONSTANT              3.0538E+07\n"+
      "ZEROS   3\n"+
      "         0.0000E+00   0.0000E+00\n"+
      "         0.0000E+00   0.0000E+00\n"+
      "         0.0000E+00   0.0000E+00\n"+
      "POLES   5\n"+
      "        -3.7024E-02   3.7024E-02\n"+
      "        -3.7024E-02  -3.7024E-02\n"+
      "        -2.5133E+02   0.0000E+00\n"+
      "        -1.1863E+02   4.2306E+02\n"+
      "        -1.1863E+02  -4.2306E+02\n"+
      "* <EOE>\n"+
      "* <EOR>\n");
    try {Thread.sleep(10000);} catch(InterruptedException e) {}
    System.exit(0);
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton dismiss;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextPane text;
  // End of variables declaration//GEN-END:variables
  
}
