/*
 *  This software is in the public domain because it contains materials 
 *  that originally came from the United States Geological Survey, 
 *  an agency of the United States Department of Interior. For more 
 *  information, see the official USGS copyright policy at 
 *  http://www.usgs.gov/visual-id/credit_usgs.html#copyright
 */
package gov.usgs.edge.config;

/**
 *
 * @author bmielke
 */
public class SubspaceChannelDeleteErrorPanel extends javax.swing.JPanel {
  private SubspaceChannelDeletePanel scp;
  private String errorMessage;

  /**
   * Creates new form SubspaceChannelPickErrorPanel
   */
  public SubspaceChannelDeleteErrorPanel(SubspaceChannelDeletePanel scp, String errorMessage) {
    this.scp = scp;
    this.errorMessage = errorMessage;
    gov.usgs.edge.config.UC.Look(this);
    initComponents();
    errorLabel.setText(errorMessage);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    errorLabel = new javax.swing.JLabel();
    errorOkButton = new javax.swing.JButton();

    errorLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
    errorLabel.setForeground(new java.awt.Color(255, 51, 51));
    errorLabel.setText("Error Message");
    errorLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

    errorOkButton.setText("OK");
    errorOkButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        errorOkButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(52, 52, 52)
            .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGap(136, 136, 136)
            .addComponent(errorOkButton)))
        .addContainerGap(70, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(errorOkButton)
        .addContainerGap(193, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void errorOkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorOkButtonActionPerformed
    // TODO add your handling code here:
    scp.setAreaID(0);
  }//GEN-LAST:event_errorOkButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel errorLabel;
  private javax.swing.JButton errorOkButton;
  // End of variables declaration//GEN-END:variables
}
