/*
 *  This software is in the public domain because it contains materials 
 *  that originally came from the United States Geological Survey, 
 *  an agency of the United States Department of Interior. For more 
 *  information, see the official USGS copyright policy at 
 *  http://www.usgs.gov/visual-id/credit_usgs.html#copyright
 */
package gov.usgs.edge.config;
import gov.usgs.anss.util.ErrorTrack;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
/**
 *
 * @author U.S. Geological Survey  <ketchum at usgs.gov>
 */
public final class SubspaceEventChannelPanel extends javax.swing.JPanel {
  SubspaceEventChannel chan;
  SubspaceEvent event;
  public SubspaceEventChannel getSubspaceEventChannel() {return chan;}
  /**
   * Creates new form SubspaceChannelPanel
   *@param ch An SubspaceChannel to display
   *@param e The event this channel is associated with
   */
  public SubspaceEventChannelPanel(SubspaceEventChannel ch, SubspaceEvent e) {
    initComponents();
    if(ch != null) chan = ch;
    if(e != null) event = e;
    doOldOne();
  }
  public void reload(ResultSet rs ) throws SQLException {
    chan = new SubspaceEventChannel(rs);
    doOldOne();
  }
  public void chkForm(ErrorTrack err) {
  }
  /** Update the current GUI fields to DB for this channel
   * 
   *@param db A database statement to use
   *@throws SQLException 
   */
  public void updateRecord(Statement db) throws SQLException {
    String s = "UPDATE edge.subspaceeventchannel SET disable="+(disable.isSelected()?"1":"0")+
            ",reference="+(reference.isSelected()?"1":"0")+
            ",updated=now() WHERE id="+chan.getID();
    chan.setDisabled(disable.isSelected());
    chan.setReference(reference.isSelected());
    db.executeUpdate(s);
            
  }
  private void doOldOne() {
    gov.usgs.edge.config.UC.Look(this);

    disable.setSelected(chan.isDisabled());
    reference.setSelected(chan.isReference());
    channelText.setText(chan.getFixedToString().toString()+" "+event.getSubspaceEvent());
    channelText.setCaretPosition(0);
  }
  
  private void updateFromPanel() {
    chan.setDisabled(disable.isSelected());
    chan.setReference(reference.isSelected());
  }
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    disable = new javax.swing.JCheckBox();
    reference = new javax.swing.JCheckBox();
    channelText = new javax.swing.JTextField();

    setMinimumSize(new java.awt.Dimension(320, 26));
    setName(""); // NOI18N
    setPreferredSize(new java.awt.Dimension(320, 26));
    setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 2));

    disable.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
    disable.setText("Dsbl");
    disable.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        disableActionPerformed(evt);
      }
    });
    add(disable);

    reference.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
    reference.setText("Ref");
    reference.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        referenceActionPerformed(evt);
      }
    });
    add(reference);

    channelText.setEditable(false);
    channelText.setFont(new java.awt.Font("Monospaced", 0, 10)); // NOI18N
    channelText.setToolTipText("Information about this quake is here");
    channelText.setMinimumSize(new java.awt.Dimension(200, 26));
    channelText.setPreferredSize(new java.awt.Dimension(200, 26));
    add(channelText);
  }// </editor-fold>//GEN-END:initComponents

  private void disableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disableActionPerformed
    updateFromPanel();
  }//GEN-LAST:event_disableActionPerformed

  private void referenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceActionPerformed
    updateFromPanel();
  }//GEN-LAST:event_referenceActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField channelText;
  private javax.swing.JCheckBox disable;
  private javax.swing.JCheckBox reference;
  // End of variables declaration//GEN-END:variables
}
