/*
 *  This software is in the public domain because it contains materials 
 *  that originally came from the United States Geological Survey, 
 *  an agency of the United States Department of Interior. For more 
 *  information, see the official USGS copyright policy at 
 *  http://www.usgs.gov/visual-id/credit_usgs.html#copyright
 */
package gov.usgs.edge.config;

/**
 *
 * @author bmielke
 */
public class SubspaceChannelDeleteSubPanel extends javax.swing.JPanel {

  private SubspaceChannel subspaceChannel;
  private SubspaceChannelDeletePanel subspaceChannelPickPanel;
  
  /**
   * Creates new form SubspaceChannelPickSubPanel
   */
  public SubspaceChannelDeleteSubPanel(SubspaceChannel subspaceChannel,SubspaceChannelDeletePanel subspaceChannelPickPanel) {
    this.subspaceChannel = subspaceChannel;
    this.subspaceChannelPickPanel = subspaceChannelPickPanel;
    gov.usgs.edge.config.UC.Look(this);
    initComponents();
    initFields();
  }
  
  private void initFields() {    
    removeCheckbox.setSelected(false);
    channelText.setText(subspaceChannel.toString());
  }
  
  public boolean isSelected() {
    return removeCheckbox.isSelected();
  }
  
  public int getChannelId()  {
    return subspaceChannel.getID();
  }
  
  public int getAreaId() {
    return subspaceChannel.getAreaID();
  }
  
  public String getName() {
    return subspaceChannel.toString();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    removeCheckbox = new javax.swing.JCheckBox();
    channelText = new javax.swing.JTextField();

    setMinimumSize(new java.awt.Dimension(234, 26));
    setPreferredSize(new java.awt.Dimension(275, 26));
    setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 2));

    removeCheckbox.setText("Remove");
    removeCheckbox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        removeCheckboxActionPerformed(evt);
      }
    });
    add(removeCheckbox);

    channelText.setEditable(false);
    channelText.setMinimumSize(new java.awt.Dimension(150, 26));
    channelText.setPreferredSize(new java.awt.Dimension(150, 26));
    add(channelText);
  }// </editor-fold>//GEN-END:initComponents

  private void removeCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeCheckboxActionPerformed
    // TODO add your handling code here:
    this.subspaceChannelPickPanel.updateRemoveButton();
  }//GEN-LAST:event_removeCheckboxActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextField channelText;
  private javax.swing.JCheckBox removeCheckbox;
  // End of variables declaration//GEN-END:variables
}
